use wasmparser::Operator as LibOp;

#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum Instruction {
    Local(LocalDefinition),
    Body(BodyInstruction),
}

impl Instruction {
    #[must_use]
    pub fn new_local(count: u32, ty: ValType) -> Self {
        Instruction::Local(LocalDefinition { count, ty })
    }

    #[must_use]
    pub fn new_body(operator: BodyInstruction) -> Self {
        Instruction::Body(operator)
    }
}

#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub struct LocalDefinition {
    pub count: u32,
    pub ty: ValType,
}

#[derive(Debug, Clone, Hash, PartialEq, Eq)]
pub enum ValType {
    I32,
    I64,
    F32,
    F64,
    V128,
    Ref,
}

impl From<wasmparser::ValType> for ValType {
    fn from(value: wasmparser::ValType) -> Self {
        match value {
            wasmparser::ValType::I32 => ValType::I32,
            wasmparser::ValType::I64 => ValType::I64,
            wasmparser::ValType::F32 => ValType::F32,
            wasmparser::ValType::F64 => ValType::F64,
            wasmparser::ValType::V128 => ValType::V128,
            wasmparser::ValType::Ref(_ref_type) => ValType::Ref,
        }
    }
}

macro_rules! impl_body_instructions {
    ($($variant:ident),* $(,)?) => {
        #[derive(Debug, Clone, Hash, PartialEq, Eq)]
        pub enum BodyInstruction {
            $($variant),*
        }

        impl From<&LibOp<'_>> for BodyInstruction {
            #[allow(clippy::too_many_lines)]
            fn from(value: &LibOp) -> Self {
                match value {
                    $(
                        LibOp::$variant {..} => BodyInstruction::$variant,
                    )*
                    // The Wasm instruction set is non-exhaustive, the `todo`
                    // catches future additions to the spec.
                    _ => todo!(),
                }
            }
        }
    }
}

impl_body_instructions! {
    Unreachable,
    Nop,
    Block,
    Loop,
    If,
    Else,
    End,
    Br,
    BrIf,
    BrTable,
    Return,
    Call,
    CallIndirect,
    Drop,
    Select,
    LocalGet,
    LocalSet,
    LocalTee,
    GlobalGet,
    GlobalSet,
    I32Load,
    I64Load,
    F32Load,
    F64Load,
    I32Load8S,
    I32Load8U,
    I32Load16S,
    I32Load16U,
    I64Load8S,
    I64Load8U,
    I64Load16S,
    I64Load16U,
    I64Load32S,
    I64Load32U,
    I32Store,
    I64Store,
    F32Store,
    F64Store,
    I32Store8,
    I32Store16,
    I64Store8,
    I64Store16,
    I64Store32,
    MemorySize,
    MemoryGrow,
    I32Const,
    I64Const,
    F32Const,
    F64Const,
    I32Eqz,
    I32Eq,
    I32Ne,
    I32LtS,
    I32LtU,
    I32GtS,
    I32GtU,
    I32LeS,
    I32LeU,
    I32GeS,
    I32GeU,
    I64Eqz,
    I64Eq,
    I64Ne,
    I64LtS,
    I64LtU,
    I64GtS,
    I64GtU,
    I64LeS,
    I64LeU,
    I64GeS,
    I64GeU,
    F32Eq,
    F32Ne,
    F32Lt,
    F32Gt,
    F32Le,
    F32Ge,
    F64Eq,
    F64Ne,
    F64Lt,
    F64Gt,
    F64Le,
    F64Ge,
    I32Clz,
    I32Ctz,
    I32Popcnt,
    I32Add,
    I32Sub,
    I32Mul,
    I32DivS,
    I32DivU,
    I32RemS,
    I32RemU,
    I32And,
    I32Or,
    I32Xor,
    I32Shl,
    I32ShrS,
    I32ShrU,
    I32Rotl,
    I32Rotr,
    I64Clz,
    I64Ctz,
    I64Popcnt,
    I64Add,
    I64Sub,
    I64Mul,
    I64DivS,
    I64DivU,
    I64RemS,
    I64RemU,
    I64And,
    I64Or,
    I64Xor,
    I64Shl,
    I64ShrS,
    I64ShrU,
    I64Rotl,
    I64Rotr,
    F32Abs,
    F32Neg,
    F32Ceil,
    F32Floor,
    F32Trunc,
    F32Nearest,
    F32Sqrt,
    F32Add,
    F32Sub,
    F32Mul,
    F32Div,
    F32Min,
    F32Max,
    F32Copysign,
    F64Abs,
    F64Neg,
    F64Ceil,
    F64Floor,
    F64Trunc,
    F64Nearest,
    F64Sqrt,
    F64Add,
    F64Sub,
    F64Mul,
    F64Div,
    F64Min,
    F64Max,
    F64Copysign,
    I32WrapI64,
    I32TruncF32S,
    I32TruncF32U,
    I32TruncF64S,
    I32TruncF64U,
    I64ExtendI32S,
    I64ExtendI32U,
    I64TruncF32S,
    I64TruncF32U,
    I64TruncF64S,
    I64TruncF64U,
    F32ConvertI32S,
    F32ConvertI32U,
    F32ConvertI64S,
    F32ConvertI64U,
    F32DemoteF64,
    F64ConvertI32S,
    F64ConvertI32U,
    F64ConvertI64S,
    F64ConvertI64U,
    F64PromoteF32,
    I32ReinterpretF32,
    I64ReinterpretF64,
    F32ReinterpretI32,
    F64ReinterpretI64,
    I32Extend8S,
    I32Extend16S,
    I64Extend8S,
    I64Extend16S,
    I64Extend32S,
    RefEq,
    StructNew,
    StructNewDefault,
    StructGet,
    StructGetS,
    StructGetU,
    StructSet,
    ArrayNew,
    ArrayNewDefault,
    ArrayNewFixed,
    ArrayNewData,
    ArrayNewElem,
    ArrayGet,
    ArrayGetS,
    ArrayGetU,
    ArraySet,
    ArrayLen,
    ArrayFill,
    ArrayCopy,
    ArrayInitData,
    ArrayInitElem,
    RefTestNonNull,
    RefTestNullable,
    RefCastNonNull,
    RefCastNullable,
    BrOnCast,
    BrOnCastFail,
    AnyConvertExtern,
    ExternConvertAny,
    RefI31,
    I31GetS,
    I31GetU,
    I32TruncSatF32S,
    I32TruncSatF32U,
    I32TruncSatF64S,
    I32TruncSatF64U,
    I64TruncSatF32S,
    I64TruncSatF32U,
    I64TruncSatF64S,
    I64TruncSatF64U,
    MemoryInit,
    DataDrop,
    MemoryCopy,
    MemoryFill,
    TableInit,
    ElemDrop,
    TableCopy,
    TypedSelect,
    TypedSelectMulti,
    RefNull,
    RefIsNull,
    RefFunc,
    TableFill,
    TableGet,
    TableSet,
    TableGrow,
    TableSize,
    ReturnCall,
    ReturnCallIndirect,
    MemoryDiscard,
    MemoryAtomicNotify,
    MemoryAtomicWait32,
    MemoryAtomicWait64,
    AtomicFence,
    I32AtomicLoad,
    I64AtomicLoad,
    I32AtomicLoad8U,
    I32AtomicLoad16U,
    I64AtomicLoad8U,
    I64AtomicLoad16U,
    I64AtomicLoad32U,
    I32AtomicStore,
    I64AtomicStore,
    I32AtomicStore8,
    I32AtomicStore16,
    I64AtomicStore8,
    I64AtomicStore16,
    I64AtomicStore32,
    I32AtomicRmwAdd,
    I64AtomicRmwAdd,
    I32AtomicRmw8AddU,
    I32AtomicRmw16AddU,
    I64AtomicRmw8AddU,
    I64AtomicRmw16AddU,
    I64AtomicRmw32AddU,
    I32AtomicRmwSub,
    I64AtomicRmwSub,
    I32AtomicRmw8SubU,
    I32AtomicRmw16SubU,
    I64AtomicRmw8SubU,
    I64AtomicRmw16SubU,
    I64AtomicRmw32SubU,
    I32AtomicRmwAnd,
    I64AtomicRmwAnd,
    I32AtomicRmw8AndU,
    I32AtomicRmw16AndU,
    I64AtomicRmw8AndU,
    I64AtomicRmw16AndU,
    I64AtomicRmw32AndU,
    I32AtomicRmwOr,
    I64AtomicRmwOr,
    I32AtomicRmw8OrU,
    I32AtomicRmw16OrU,
    I64AtomicRmw8OrU,
    I64AtomicRmw16OrU,
    I64AtomicRmw32OrU,
    I32AtomicRmwXor,
    I64AtomicRmwXor,
    I32AtomicRmw8XorU,
    I32AtomicRmw16XorU,
    I64AtomicRmw8XorU,
    I64AtomicRmw16XorU,
    I64AtomicRmw32XorU,
    I32AtomicRmwXchg,
    I64AtomicRmwXchg,
    I32AtomicRmw8XchgU,
    I32AtomicRmw16XchgU,
    I64AtomicRmw8XchgU,
    I64AtomicRmw16XchgU,
    I64AtomicRmw32XchgU,
    I32AtomicRmwCmpxchg,
    I64AtomicRmwCmpxchg,
    I32AtomicRmw8CmpxchgU,
    I32AtomicRmw16CmpxchgU,
    I64AtomicRmw8CmpxchgU,
    I64AtomicRmw16CmpxchgU,
    I64AtomicRmw32CmpxchgU,
    V128Load,
    V128Load8x8S,
    V128Load8x8U,
    V128Load16x4S,
    V128Load16x4U,
    V128Load32x2S,
    V128Load32x2U,
    V128Load8Splat,
    V128Load16Splat,
    V128Load32Splat,
    V128Load64Splat,
    V128Load32Zero,
    V128Load64Zero,
    V128Store,
    V128Load8Lane,
    V128Load16Lane,
    V128Load32Lane,
    V128Load64Lane,
    V128Store8Lane,
    V128Store16Lane,
    V128Store32Lane,
    V128Store64Lane,
    V128Const,
    I8x16Shuffle,
    I8x16ExtractLaneS,
    I8x16ExtractLaneU,
    I8x16ReplaceLane,
    I16x8ExtractLaneS,
    I16x8ExtractLaneU,
    I16x8ReplaceLane,
    I32x4ExtractLane,
    I32x4ReplaceLane,
    I64x2ExtractLane,
    I64x2ReplaceLane,
    F32x4ExtractLane,
    F32x4ReplaceLane,
    F64x2ExtractLane,
    F64x2ReplaceLane,
    I8x16Swizzle,
    I8x16Splat,
    I16x8Splat,
    I32x4Splat,
    I64x2Splat,
    F32x4Splat,
    F64x2Splat,
    I8x16Eq,
    I8x16Ne,
    I8x16LtS,
    I8x16LtU,
    I8x16GtS,
    I8x16GtU,
    I8x16LeS,
    I8x16LeU,
    I8x16GeS,
    I8x16GeU,
    I16x8Eq,
    I16x8Ne,
    I16x8LtS,
    I16x8LtU,
    I16x8GtS,
    I16x8GtU,
    I16x8LeS,
    I16x8LeU,
    I16x8GeS,
    I16x8GeU,
    I32x4Eq,
    I32x4Ne,
    I32x4LtS,
    I32x4LtU,
    I32x4GtS,
    I32x4GtU,
    I32x4LeS,
    I32x4LeU,
    I32x4GeS,
    I32x4GeU,
    I64x2Eq,
    I64x2Ne,
    I64x2LtS,
    I64x2GtS,
    I64x2LeS,
    I64x2GeS,
    F32x4Eq,
    F32x4Ne,
    F32x4Lt,
    F32x4Gt,
    F32x4Le,
    F32x4Ge,
    F64x2Eq,
    F64x2Ne,
    F64x2Lt,
    F64x2Gt,
    F64x2Le,
    F64x2Ge,
    V128Not,
    V128And,
    V128AndNot,
    V128Or,
    V128Xor,
    V128Bitselect,
    V128AnyTrue,
    I8x16Abs,
    I8x16Neg,
    I8x16Popcnt,
    I8x16AllTrue,
    I8x16Bitmask,
    I8x16NarrowI16x8S,
    I8x16NarrowI16x8U,
    I8x16Shl,
    I8x16ShrS,
    I8x16ShrU,
    I8x16Add,
    I8x16AddSatS,
    I8x16AddSatU,
    I8x16Sub,
    I8x16SubSatS,
    I8x16SubSatU,
    I8x16MinS,
    I8x16MinU,
    I8x16MaxS,
    I8x16MaxU,
    I8x16AvgrU,
    I16x8ExtAddPairwiseI8x16S,
    I16x8ExtAddPairwiseI8x16U,
    I16x8Abs,
    I16x8Neg,
    I16x8Q15MulrSatS,
    I16x8AllTrue,
    I16x8Bitmask,
    I16x8NarrowI32x4S,
    I16x8NarrowI32x4U,
    I16x8ExtendLowI8x16S,
    I16x8ExtendHighI8x16S,
    I16x8ExtendLowI8x16U,
    I16x8ExtendHighI8x16U,
    I16x8Shl,
    I16x8ShrS,
    I16x8ShrU,
    I16x8Add,
    I16x8AddSatS,
    I16x8AddSatU,
    I16x8Sub,
    I16x8SubSatS,
    I16x8SubSatU,
    I16x8Mul,
    I16x8MinS,
    I16x8MinU,
    I16x8MaxS,
    I16x8MaxU,
    I16x8AvgrU,
    I16x8ExtMulLowI8x16S,
    I16x8ExtMulHighI8x16S,
    I16x8ExtMulLowI8x16U,
    I16x8ExtMulHighI8x16U,
    I32x4ExtAddPairwiseI16x8S,
    I32x4ExtAddPairwiseI16x8U,
    I32x4Abs,
    I32x4Neg,
    I32x4AllTrue,
    I32x4Bitmask,
    I32x4ExtendLowI16x8S,
    I32x4ExtendHighI16x8S,
    I32x4ExtendLowI16x8U,
    I32x4ExtendHighI16x8U,
    I32x4Shl,
    I32x4ShrS,
    I32x4ShrU,
    I32x4Add,
    I32x4Sub,
    I32x4Mul,
    I32x4MinS,
    I32x4MinU,
    I32x4MaxS,
    I32x4MaxU,
    I32x4DotI16x8S,
    I32x4ExtMulLowI16x8S,
    I32x4ExtMulHighI16x8S,
    I32x4ExtMulLowI16x8U,
    I32x4ExtMulHighI16x8U,
    I64x2Abs,
    I64x2Neg,
    I64x2AllTrue,
    I64x2Bitmask,
    I64x2ExtendLowI32x4S,
    I64x2ExtendHighI32x4S,
    I64x2ExtendLowI32x4U,
    I64x2ExtendHighI32x4U,
    I64x2Shl,
    I64x2ShrS,
    I64x2ShrU,
    I64x2Add,
    I64x2Sub,
    I64x2Mul,
    I64x2ExtMulLowI32x4S,
    I64x2ExtMulHighI32x4S,
    I64x2ExtMulLowI32x4U,
    I64x2ExtMulHighI32x4U,
    F32x4Ceil,
    F32x4Floor,
    F32x4Trunc,
    F32x4Nearest,
    F32x4Abs,
    F32x4Neg,
    F32x4Sqrt,
    F32x4Add,
    F32x4Sub,
    F32x4Mul,
    F32x4Div,
    F32x4Min,
    F32x4Max,
    F32x4PMin,
    F32x4PMax,
    F64x2Ceil,
    F64x2Floor,
    F64x2Trunc,
    F64x2Nearest,
    F64x2Abs,
    F64x2Neg,
    F64x2Sqrt,
    F64x2Add,
    F64x2Sub,
    F64x2Mul,
    F64x2Div,
    F64x2Min,
    F64x2Max,
    F64x2PMin,
    F64x2PMax,
    I32x4TruncSatF32x4S,
    I32x4TruncSatF32x4U,
    F32x4ConvertI32x4S,
    F32x4ConvertI32x4U,
    I32x4TruncSatF64x2SZero,
    I32x4TruncSatF64x2UZero,
    F64x2ConvertLowI32x4S,
    F64x2ConvertLowI32x4U,
    F32x4DemoteF64x2Zero,
    F64x2PromoteLowF32x4,
    I8x16RelaxedSwizzle,
    I32x4RelaxedTruncF32x4S,
    I32x4RelaxedTruncF32x4U,
    I32x4RelaxedTruncF64x2SZero,
    I32x4RelaxedTruncF64x2UZero,
    F32x4RelaxedMadd,
    F32x4RelaxedNmadd,
    F64x2RelaxedMadd,
    F64x2RelaxedNmadd,
    I8x16RelaxedLaneselect,
    I16x8RelaxedLaneselect,
    I32x4RelaxedLaneselect,
    I64x2RelaxedLaneselect,
    F32x4RelaxedMin,
    F32x4RelaxedMax,
    F64x2RelaxedMin,
    F64x2RelaxedMax,
    I16x8RelaxedQ15mulrS,
    I16x8RelaxedDotI8x16I7x16S,
    I32x4RelaxedDotI8x16I7x16AddS,
    TryTable,
    Throw,
    ThrowRef,
    Try,
    Catch,
    Rethrow,
    Delegate,
    CatchAll,
    GlobalAtomicGet,
    GlobalAtomicSet,
    GlobalAtomicRmwAdd,
    GlobalAtomicRmwSub,
    GlobalAtomicRmwAnd,
    GlobalAtomicRmwOr,
    GlobalAtomicRmwXor,
    GlobalAtomicRmwXchg,
    GlobalAtomicRmwCmpxchg,
    TableAtomicGet,
    TableAtomicSet,
    TableAtomicRmwXchg,
    TableAtomicRmwCmpxchg,
    StructAtomicGet,
    StructAtomicGetS,
    StructAtomicGetU,
    StructAtomicSet,
    StructAtomicRmwAdd,
    StructAtomicRmwSub,
    StructAtomicRmwAnd,
    StructAtomicRmwOr,
    StructAtomicRmwXor,
    StructAtomicRmwXchg,
    StructAtomicRmwCmpxchg,
    ArrayAtomicGet,
    ArrayAtomicGetS,
    ArrayAtomicGetU,
    ArrayAtomicSet,
    ArrayAtomicRmwAdd,
    ArrayAtomicRmwSub,
    ArrayAtomicRmwAnd,
    ArrayAtomicRmwOr,
    ArrayAtomicRmwXor,
    ArrayAtomicRmwXchg,
    ArrayAtomicRmwCmpxchg,
    RefI31Shared,
    CallRef,
    ReturnCallRef,
    RefAsNonNull,
    BrOnNull,
    BrOnNonNull,
    ContNew,
    ContBind,
    Suspend,
    Resume,
    ResumeThrow,
    Switch,
    I64Add128,
    I64Sub128,
    I64MulWideS,
    I64MulWideU,
}

impl BodyInstruction {
    #[allow(clippy::too_many_lines)]
    #[must_use]
    pub fn to_wat_instr(&self) -> &'static str {
        match self {
            BodyInstruction::Unreachable => "unreachable",
            BodyInstruction::Nop => "nop",
            BodyInstruction::Block => "block",
            BodyInstruction::Loop => "loop",
            BodyInstruction::If => "if",
            BodyInstruction::Else => "else",
            BodyInstruction::End => "end",
            BodyInstruction::Br => "br",
            BodyInstruction::BrIf => "br_if",
            BodyInstruction::BrTable => "br_table",
            BodyInstruction::Return => "return",
            BodyInstruction::Call => "call",
            BodyInstruction::CallIndirect => "call_indirect",
            BodyInstruction::Drop => "drop",
            BodyInstruction::Select
            | BodyInstruction::TypedSelect
            | BodyInstruction::TypedSelectMulti => "select",
            BodyInstruction::LocalGet => "local.get",
            BodyInstruction::LocalSet => "local.set",
            BodyInstruction::LocalTee => "local.tee",
            BodyInstruction::GlobalGet => "global.get",
            BodyInstruction::GlobalSet => "global.set",
            BodyInstruction::I32Load => "i32.load",
            BodyInstruction::I64Load => "i64.load",
            BodyInstruction::F32Load => "f32.load",
            BodyInstruction::F64Load => "f64.load",
            BodyInstruction::I32Load8S => "i32.load8_s",
            BodyInstruction::I32Load8U => "i32.load8_u",
            BodyInstruction::I32Load16S => "i32.load16_s",
            BodyInstruction::I32Load16U => "i32.load16_u",
            BodyInstruction::I64Load8S => "i64.load8_s",
            BodyInstruction::I64Load8U => "i64.load8_u",
            BodyInstruction::I64Load16S => "i64.load16_s",
            BodyInstruction::I64Load16U => "i64.load16_u",
            BodyInstruction::I64Load32S => "i64.load32_s",
            BodyInstruction::I64Load32U => "i64.load32_u",
            BodyInstruction::I32Store => "i32.store",
            BodyInstruction::I64Store => "i64.store",
            BodyInstruction::F32Store => "f32.store",
            BodyInstruction::F64Store => "f64.store",
            BodyInstruction::I32Store8 => "i32.store8",
            BodyInstruction::I32Store16 => "i32.store16",
            BodyInstruction::I64Store8 => "i64.store8",
            BodyInstruction::I64Store16 => "i64.store16",
            BodyInstruction::I64Store32 => "i64.store32",
            BodyInstruction::MemorySize => "memory.size",
            BodyInstruction::MemoryGrow => "memory.grow",
            BodyInstruction::I32Const => "i32.const",
            BodyInstruction::I64Const => "i64.const",
            BodyInstruction::F32Const => "f32.const",
            BodyInstruction::F64Const => "f64.const",
            BodyInstruction::I32Eqz => "i32.eqz",
            BodyInstruction::I32Eq => "i32.eq",
            BodyInstruction::I32Ne => "i32.ne",
            BodyInstruction::I32LtS => "i32.lt_s",
            BodyInstruction::I32LtU => "i32.lt_u",
            BodyInstruction::I32GtS => "i32.gt_s",
            BodyInstruction::I32GtU => "i32.gt_u",
            BodyInstruction::I32LeS => "i32.le_s",
            BodyInstruction::I32LeU => "i32.le_u",
            BodyInstruction::I32GeS => "i32.ge_s",
            BodyInstruction::I32GeU => "i32.ge_u",
            BodyInstruction::I64Eqz => "i64.eqz",
            BodyInstruction::I64Eq => "i64.eq",
            BodyInstruction::I64Ne => "i64.ne",
            BodyInstruction::I64LtS => "i64.lt_s",
            BodyInstruction::I64LtU => "i64.lt_u",
            BodyInstruction::I64GtS => "i64.gt_s",
            BodyInstruction::I64GtU => "i64.gt_u",
            BodyInstruction::I64LeS => "i64.le_s",
            BodyInstruction::I64LeU => "i64.le_u",
            BodyInstruction::I64GeS => "i64.ge_s",
            BodyInstruction::I64GeU => "i64.ge_u",
            BodyInstruction::F32Eq => "f32.eq",
            BodyInstruction::F32Ne => "f32.ne",
            BodyInstruction::F32Lt => "f32.lt",
            BodyInstruction::F32Gt => "f32.gt",
            BodyInstruction::F32Le => "f32.le",
            BodyInstruction::F32Ge => "f32.ge",
            BodyInstruction::F64Eq => "f64.eq",
            BodyInstruction::F64Ne => "f64.ne",
            BodyInstruction::F64Lt => "f64.lt",
            BodyInstruction::F64Gt => "f64.gt",
            BodyInstruction::F64Le => "f64.le",
            BodyInstruction::F64Ge => "f64.ge",
            BodyInstruction::I32Clz => "i32.clz",
            BodyInstruction::I32Ctz => "i32.ctz",
            BodyInstruction::I32Popcnt => "i32.popcnt",
            BodyInstruction::I32Add => "i32.add",
            BodyInstruction::I32Sub => "i32.sub",
            BodyInstruction::I32Mul => "i32.mul",
            BodyInstruction::I32DivS => "i32.div_s",
            BodyInstruction::I32DivU => "i32.div_u",
            BodyInstruction::I32RemS => "i32.rem_s",
            BodyInstruction::I32RemU => "i32.rem_u",
            BodyInstruction::I32And => "i32.and",
            BodyInstruction::I32Or => "i32.or",
            BodyInstruction::I32Xor => "i32.xor",
            BodyInstruction::I32Shl => "i32.shl",
            BodyInstruction::I32ShrS => "i32.shr_s",
            BodyInstruction::I32ShrU => "i32.shr_u",
            BodyInstruction::I32Rotl => "i32.rotl",
            BodyInstruction::I32Rotr => "i32.rotr",
            BodyInstruction::I64Clz => "i64.clz",
            BodyInstruction::I64Ctz => "i64.ctz",
            BodyInstruction::I64Popcnt => "i64.popcnt",
            BodyInstruction::I64Add => "i64.add",
            BodyInstruction::I64Sub => "i64.sub",
            BodyInstruction::I64Mul => "i64.mul",
            BodyInstruction::I64DivS => "i64.div_s",
            BodyInstruction::I64DivU => "i64.div_u",
            BodyInstruction::I64RemS => "i64.rem_s",
            BodyInstruction::I64RemU => "i64.rem_u",
            BodyInstruction::I64And => "i64.and",
            BodyInstruction::I64Or => "i64.or",
            BodyInstruction::I64Xor => "i64.xor",
            BodyInstruction::I64Shl => "i64.shl",
            BodyInstruction::I64ShrS => "i64.shr_s",
            BodyInstruction::I64ShrU => "i64.shr_u",
            BodyInstruction::I64Rotl => "i64.rotl",
            BodyInstruction::I64Rotr => "i64.rotr",
            BodyInstruction::F32Abs => "f32.abs",
            BodyInstruction::F32Neg => "f32.neg",
            BodyInstruction::F32Ceil => "f32.ceil",
            BodyInstruction::F32Floor => "f32.floor",
            BodyInstruction::F32Trunc => "f32.trunc",
            BodyInstruction::F32Nearest => "f32.nearest",
            BodyInstruction::F32Sqrt => "f32.sqrt",
            BodyInstruction::F32Add => "f32.add",
            BodyInstruction::F32Sub => "f32.sub",
            BodyInstruction::F32Mul => "f32.mul",
            BodyInstruction::F32Div => "f32.div",
            BodyInstruction::F32Min => "f32.min",
            BodyInstruction::F32Max => "f32.max",
            BodyInstruction::F32Copysign => "f32.copysign",
            BodyInstruction::F64Abs => "f64.abs",
            BodyInstruction::F64Neg => "f64.neg",
            BodyInstruction::F64Ceil => "f64.ceil",
            BodyInstruction::F64Floor => "f64.floor",
            BodyInstruction::F64Trunc => "f64.trunc",
            BodyInstruction::F64Nearest => "f64.nearest",
            BodyInstruction::F64Sqrt => "f64.sqrt",
            BodyInstruction::F64Add => "f64.add",
            BodyInstruction::F64Sub => "f64.sub",
            BodyInstruction::F64Mul => "f64.mul",
            BodyInstruction::F64Div => "f64.div",
            BodyInstruction::F64Min => "f64.min",
            BodyInstruction::F64Max => "f64.max",
            BodyInstruction::F64Copysign => "f64.copysign",
            BodyInstruction::I32WrapI64 => "i32.wrap_i64",
            BodyInstruction::I32TruncF32S => "i32.trunc_f32_s",
            BodyInstruction::I32TruncF32U => "i32.trunc_f32_u",
            BodyInstruction::I32TruncF64S => "i32.trunc_f64_s",
            BodyInstruction::I32TruncF64U => "i32.trunc_f64_u",
            BodyInstruction::I64ExtendI32S => "i64.extend_i32_s",
            BodyInstruction::I64ExtendI32U => "i64.extend_i32_u",
            BodyInstruction::I64TruncF32S => "i64.trunc_f32_s",
            BodyInstruction::I64TruncF32U => "i64.trunc_f32_u",
            BodyInstruction::I64TruncF64S => "i64.trunc_f64_s",
            BodyInstruction::I64TruncF64U => "i64.trunc_f64_u",
            BodyInstruction::F32ConvertI32S => "f32.convert_i32_s",
            BodyInstruction::F32ConvertI32U => "f32.convert_i32_u",
            BodyInstruction::F32ConvertI64S => "f32.convert_i64_s",
            BodyInstruction::F32ConvertI64U => "f32.convert_i64_u",
            BodyInstruction::F32DemoteF64 => "f32.demote_f64",
            BodyInstruction::F64ConvertI32S => "f64.convert_i32_s",
            BodyInstruction::F64ConvertI32U => "f64.convert_i32_u",
            BodyInstruction::F64ConvertI64S => "f64.convert_i64_s",
            BodyInstruction::F64ConvertI64U => "f64.convert_i64_u",
            BodyInstruction::F64PromoteF32 => "f64.promote_f32",
            BodyInstruction::I32ReinterpretF32 => "i32.reinterpret_f32",
            BodyInstruction::I64ReinterpretF64 => "i64.reinterpret_f64",
            BodyInstruction::F32ReinterpretI32 => "f32.reinterpret_i32",
            BodyInstruction::F64ReinterpretI64 => "f64.reinterpret_i64",
            BodyInstruction::I32Extend8S => "i32.extend8_s",
            BodyInstruction::I32Extend16S => "i32.extend16_s",
            BodyInstruction::I64Extend8S => "i64.extend8_s",
            BodyInstruction::I64Extend16S => "i64.extend16_s",
            BodyInstruction::I64Extend32S => "i64.extend32_s",
            BodyInstruction::RefEq => "ref.eq",
            BodyInstruction::StructNew => "struct.new",
            BodyInstruction::StructNewDefault => "struct.new_default",
            BodyInstruction::StructGet => "struct.get",
            BodyInstruction::StructGetS => "struct.get_s",
            BodyInstruction::StructGetU => "struct.get_u",
            BodyInstruction::StructSet => "struct.set",
            BodyInstruction::ArrayNew => "array.new",
            BodyInstruction::ArrayNewDefault => "array.new_default",
            BodyInstruction::ArrayNewFixed => "array.new_fixed",
            BodyInstruction::ArrayNewData => "array.new_data",
            BodyInstruction::ArrayNewElem => "array.new_elem",
            BodyInstruction::ArrayGet => "array.get",
            BodyInstruction::ArrayGetS => "array.get_s",
            BodyInstruction::ArrayGetU => "array.get_u",
            BodyInstruction::ArraySet => "array.set",
            BodyInstruction::ArrayLen => "array.len",
            BodyInstruction::ArrayFill => "array.fill",
            BodyInstruction::ArrayCopy => "array.copy",
            BodyInstruction::ArrayInitData => "array.init_data",
            BodyInstruction::ArrayInitElem => "array.init_elem",
            BodyInstruction::RefTestNonNull | BodyInstruction::RefTestNullable => "ref.test",
            BodyInstruction::RefCastNonNull | BodyInstruction::RefCastNullable => "ref.cast",
            BodyInstruction::BrOnCast => "br_on_cast",
            BodyInstruction::BrOnCastFail => "br_on_cast_fail",
            BodyInstruction::AnyConvertExtern => "any.convert_extern",
            BodyInstruction::ExternConvertAny => "extern.convert_any",
            BodyInstruction::RefI31 => "ref.i31",
            BodyInstruction::I31GetS => "i31.get_s",
            BodyInstruction::I31GetU => "i31.get_u",
            BodyInstruction::I32TruncSatF32S => "i32.trunc_sat_f32_s",
            BodyInstruction::I32TruncSatF32U => "i32.trunc_sat_f32_u",
            BodyInstruction::I32TruncSatF64S => "i32.trunc_sat_f64_s",
            BodyInstruction::I32TruncSatF64U => "i32.trunc_sat_f64_u",
            BodyInstruction::I64TruncSatF32S => "i64.trunc_sat_f32_s",
            BodyInstruction::I64TruncSatF32U => "i64.trunc_sat_f32_u",
            BodyInstruction::I64TruncSatF64S => "i64.trunc_sat_f64_s",
            BodyInstruction::I64TruncSatF64U => "i64.trunc_sat_f64_u",
            BodyInstruction::MemoryInit => "memory.init",
            BodyInstruction::DataDrop => "data.drop",
            BodyInstruction::MemoryCopy => "memory.copy",
            BodyInstruction::MemoryFill => "memory.fill",
            BodyInstruction::TableInit => "table.init",
            BodyInstruction::ElemDrop => "elem.drop",
            BodyInstruction::TableCopy => "table.copy",
            BodyInstruction::RefNull => "ref.null",
            BodyInstruction::RefIsNull => "ref.is_null",
            BodyInstruction::RefFunc => "ref.func",
            BodyInstruction::TableFill => "table.fill",
            BodyInstruction::TableGet => "table.get",
            BodyInstruction::TableSet => "table.set",
            BodyInstruction::TableGrow => "table.grow",
            BodyInstruction::TableSize => "table.size",
            BodyInstruction::ReturnCall => "return_call",
            BodyInstruction::ReturnCallIndirect => "return_call_indirect",
            BodyInstruction::MemoryDiscard => "memory.discard",
            BodyInstruction::MemoryAtomicNotify => "memory.atomic.notify",
            BodyInstruction::MemoryAtomicWait32 => "memory.atomic.wait32",
            BodyInstruction::MemoryAtomicWait64 => "memory.atomic.wait64",
            BodyInstruction::AtomicFence => "atomic.fence",
            BodyInstruction::I32AtomicLoad => "i32.atomic.load",
            BodyInstruction::I64AtomicLoad => "i64.atomic.load",
            BodyInstruction::I32AtomicLoad8U => "i32.atomic.load8_u",
            BodyInstruction::I32AtomicLoad16U => "i32.atomic.load16_u",
            BodyInstruction::I64AtomicLoad8U => "i64.atomic.load8_u",
            BodyInstruction::I64AtomicLoad16U => "i64.atomic.load16_u",
            BodyInstruction::I64AtomicLoad32U => "i64.atomic.load32_u",
            BodyInstruction::I32AtomicStore => "i32.atomic.store",
            BodyInstruction::I64AtomicStore => "i64.atomic.store",
            BodyInstruction::I32AtomicStore8 => "i32.atomic.store8",
            BodyInstruction::I32AtomicStore16 => "i32.atomic.store16",
            BodyInstruction::I64AtomicStore8 => "i64.atomic.store8",
            BodyInstruction::I64AtomicStore16 => "i64.atomic.store16",
            BodyInstruction::I64AtomicStore32 => "i64.atomic.store32",
            BodyInstruction::I32AtomicRmwAdd => "i32.atomic.rmw.add",
            BodyInstruction::I64AtomicRmwAdd => "i64.atomic.rmw.add",
            BodyInstruction::I32AtomicRmw8AddU => "i32.atomic.rmw8.add_u",
            BodyInstruction::I32AtomicRmw16AddU => "i32.atomic.rmw16.add_u",
            BodyInstruction::I64AtomicRmw8AddU => "i64.atomic.rmw8.add_u",
            BodyInstruction::I64AtomicRmw16AddU => "i64.atomic.rmw16.add_u",
            BodyInstruction::I64AtomicRmw32AddU => "i64.atomic.rmw32.add_u",
            BodyInstruction::I32AtomicRmwSub => "i32.atomic.rmw.sub",
            BodyInstruction::I64AtomicRmwSub => "i64.atomic.rmw.sub",
            BodyInstruction::I32AtomicRmw8SubU => "i32.atomic.rmw8.sub_u",
            BodyInstruction::I32AtomicRmw16SubU => "i32.atomic.rmw16.sub_u",
            BodyInstruction::I64AtomicRmw8SubU => "i64.atomic.rmw8.sub_u",
            BodyInstruction::I64AtomicRmw16SubU => "i64.atomic.rmw16.sub_u",
            BodyInstruction::I64AtomicRmw32SubU => "i64.atomic.rmw32.sub_u",
            BodyInstruction::I32AtomicRmwAnd => "i32.atomic.rmw.and",
            BodyInstruction::I64AtomicRmwAnd => "i64.atomic.rmw.and",
            BodyInstruction::I32AtomicRmw8AndU => "i32.atomic.rmw8.and_u",
            BodyInstruction::I32AtomicRmw16AndU => "i32.atomic.rmw16.and_u",
            BodyInstruction::I64AtomicRmw8AndU => "i64.atomic.rmw8.and_u",
            BodyInstruction::I64AtomicRmw16AndU => "i64.atomic.rmw16.and_u",
            BodyInstruction::I64AtomicRmw32AndU => "i64.atomic.rmw32.and_u",
            BodyInstruction::I32AtomicRmwOr => "i32.atomic.rmw.or",
            BodyInstruction::I64AtomicRmwOr => "i64.atomic.rmw.or",
            BodyInstruction::I32AtomicRmw8OrU => "i32.atomic.rmw8.or_u",
            BodyInstruction::I32AtomicRmw16OrU => "i32.atomic.rmw16.or_u",
            BodyInstruction::I64AtomicRmw8OrU => "i64.atomic.rmw8.or_u",
            BodyInstruction::I64AtomicRmw16OrU => "i64.atomic.rmw16.or_u",
            BodyInstruction::I64AtomicRmw32OrU => "i64.atomic.rmw32.or_u",
            BodyInstruction::I32AtomicRmwXor => "i32.atomic.rmw.xor",
            BodyInstruction::I64AtomicRmwXor => "i64.atomic.rmw.xor",
            BodyInstruction::I32AtomicRmw8XorU => "i32.atomic.rmw8.xor_u",
            BodyInstruction::I32AtomicRmw16XorU => "i32.atomic.rmw16.xor_u",
            BodyInstruction::I64AtomicRmw8XorU => "i64.atomic.rmw8.xor_u",
            BodyInstruction::I64AtomicRmw16XorU => "i64.atomic.rmw16.xor_u",
            BodyInstruction::I64AtomicRmw32XorU => "i64.atomic.rmw32.xor_u",
            BodyInstruction::I32AtomicRmwXchg => "i32.atomic.rmw.xchg",
            BodyInstruction::I64AtomicRmwXchg => "i64.atomic.rmw.xchg",
            BodyInstruction::I32AtomicRmw8XchgU => "i32.atomic.rmw8.xchg_u",
            BodyInstruction::I32AtomicRmw16XchgU => "i32.atomic.rmw16.xchg_u",
            BodyInstruction::I64AtomicRmw8XchgU => "i64.atomic.rmw8.xchg_u",
            BodyInstruction::I64AtomicRmw16XchgU => "i64.atomic.rmw16.xchg_u",
            BodyInstruction::I64AtomicRmw32XchgU => "i64.atomic.rmw32.xchg_u",
            BodyInstruction::I32AtomicRmwCmpxchg => "i32.atomic.rmw.cmpxchg",
            BodyInstruction::I64AtomicRmwCmpxchg => "i64.atomic.rmw.cmpxchg",
            BodyInstruction::I32AtomicRmw8CmpxchgU => "i32.atomic.rmw8.cmpxchg_u",
            BodyInstruction::I32AtomicRmw16CmpxchgU => "i32.atomic.rmw16.cmpxchg_u",
            BodyInstruction::I64AtomicRmw8CmpxchgU => "i64.atomic.rmw8.cmpxchg_u",
            BodyInstruction::I64AtomicRmw16CmpxchgU => "i64.atomic.rmw16.cmpxchg_u",
            BodyInstruction::I64AtomicRmw32CmpxchgU => "i64.atomic.rmw32.cmpxchg_u",
            BodyInstruction::V128Load => "v128.load",
            BodyInstruction::V128Load8x8S => "v128.load8x8_s",
            BodyInstruction::V128Load8x8U => "v128.load8x8_u",
            BodyInstruction::V128Load16x4S => "v128.load16x4_s",
            BodyInstruction::V128Load16x4U => "v128.load16x4_u",
            BodyInstruction::V128Load32x2S => "v128.load32x2_s",
            BodyInstruction::V128Load32x2U => "v128.load32x2_u",
            BodyInstruction::V128Load8Splat => "v128.load8_splat",
            BodyInstruction::V128Load16Splat => "v128.load16_splat",
            BodyInstruction::V128Load32Splat => "v128.load32_splat",
            BodyInstruction::V128Load64Splat => "v128.load64_splat",
            BodyInstruction::V128Load32Zero => "v128.load32_zero",
            BodyInstruction::V128Load64Zero => "v128.load64_zero",
            BodyInstruction::V128Store => "v128.store",
            BodyInstruction::V128Load8Lane => "v128.load8_lane",
            BodyInstruction::V128Load16Lane => "v128.load16_lane",
            BodyInstruction::V128Load32Lane => "v128.load32_lane",
            BodyInstruction::V128Load64Lane => "v128.load64_lane",
            BodyInstruction::V128Store8Lane => "v128.store8_lane",
            BodyInstruction::V128Store16Lane => "v128.store16_lane",
            BodyInstruction::V128Store32Lane => "v128.store32_lane",
            BodyInstruction::V128Store64Lane => "v128.store64_lane",
            BodyInstruction::V128Const => "v128.const",
            BodyInstruction::I8x16Shuffle => "i8x16.shuffle",
            BodyInstruction::I8x16ExtractLaneS => "i8x16.extract_lane_s",
            BodyInstruction::I8x16ExtractLaneU => "i8x16.extract_lane_u",
            BodyInstruction::I8x16ReplaceLane => "i8x16.replace_lane",
            BodyInstruction::I16x8ExtractLaneS => "i16x8.extract_lane_s",
            BodyInstruction::I16x8ExtractLaneU => "i16x8.extract_lane_u",
            BodyInstruction::I16x8ReplaceLane => "i16x8.replace_lane",
            BodyInstruction::I32x4ExtractLane => "i32x4.extract_lane",
            BodyInstruction::I32x4ReplaceLane => "i32x4.replace_lane",
            BodyInstruction::I64x2ExtractLane => "i64x2.extract_lane",
            BodyInstruction::I64x2ReplaceLane => "i64x2.replace_lane",
            BodyInstruction::F32x4ExtractLane => "f32x4.extract_lane",
            BodyInstruction::F32x4ReplaceLane => "f32x4.replace_lane",
            BodyInstruction::F64x2ExtractLane => "f64x2.extract_lane",
            BodyInstruction::F64x2ReplaceLane => "f64x2.replace_lane",
            BodyInstruction::I8x16Swizzle => "i8x16.swizzle",
            BodyInstruction::I8x16Splat => "i8x16.splat",
            BodyInstruction::I16x8Splat => "i16x8.splat",
            BodyInstruction::I32x4Splat => "i32x4.splat",
            BodyInstruction::I64x2Splat => "i64x2.splat",
            BodyInstruction::F32x4Splat => "f32x4.splat",
            BodyInstruction::F64x2Splat => "f64x2.splat",
            BodyInstruction::I8x16Eq => "i8x16.eq",
            BodyInstruction::I8x16Ne => "i8x16.ne",
            BodyInstruction::I8x16LtS => "i8x16.lt_s",
            BodyInstruction::I8x16LtU => "i8x16.lt_u",
            BodyInstruction::I8x16GtS => "i8x16.gt_s",
            BodyInstruction::I8x16GtU => "i8x16.gt_u",
            BodyInstruction::I8x16LeS => "i8x16.le_s",
            BodyInstruction::I8x16LeU => "i8x16.le_u",
            BodyInstruction::I8x16GeS => "i8x16.ge_s",
            BodyInstruction::I8x16GeU => "i8x16.ge_u",
            BodyInstruction::I16x8Eq => "i16x8.eq",
            BodyInstruction::I16x8Ne => "i16x8.ne",
            BodyInstruction::I16x8LtS => "i16x8.lt_s",
            BodyInstruction::I16x8LtU => "i16x8.lt_u",
            BodyInstruction::I16x8GtS => "i16x8.gt_s",
            BodyInstruction::I16x8GtU => "i16x8.gt_u",
            BodyInstruction::I16x8LeS => "i16x8.le_s",
            BodyInstruction::I16x8LeU => "i16x8.le_u",
            BodyInstruction::I16x8GeS => "i16x8.ge_s",
            BodyInstruction::I16x8GeU => "i16x8.ge_u",
            BodyInstruction::I32x4Eq => "i32x4.eq",
            BodyInstruction::I32x4Ne => "i32x4.ne",
            BodyInstruction::I32x4LtS => "i32x4.lt_s",
            BodyInstruction::I32x4LtU => "i32x4.lt_u",
            BodyInstruction::I32x4GtS => "i32x4.gt_s",
            BodyInstruction::I32x4GtU => "i32x4.gt_u",
            BodyInstruction::I32x4LeS => "i32x4.le_s",
            BodyInstruction::I32x4LeU => "i32x4.le_u",
            BodyInstruction::I32x4GeS => "i32x4.ge_s",
            BodyInstruction::I32x4GeU => "i32x4.ge_u",
            BodyInstruction::I64x2Eq => "i64x2.eq",
            BodyInstruction::I64x2Ne => "i64x2.ne",
            BodyInstruction::I64x2LtS => "i64x2.lt_s",
            BodyInstruction::I64x2GtS => "i64x2.gt_s",
            BodyInstruction::I64x2LeS => "i64x2.le_s",
            BodyInstruction::I64x2GeS => "i64x2.ge_s",
            BodyInstruction::F32x4Eq => "f32x4.eq",
            BodyInstruction::F32x4Ne => "f32x4.ne",
            BodyInstruction::F32x4Lt => "f32x4.lt",
            BodyInstruction::F32x4Gt => "f32x4.gt",
            BodyInstruction::F32x4Le => "f32x4.le",
            BodyInstruction::F32x4Ge => "f32x4.ge",
            BodyInstruction::F64x2Eq => "f64x2.eq",
            BodyInstruction::F64x2Ne => "f64x2.ne",
            BodyInstruction::F64x2Lt => "f64x2.lt",
            BodyInstruction::F64x2Gt => "f64x2.gt",
            BodyInstruction::F64x2Le => "f64x2.le",
            BodyInstruction::F64x2Ge => "f64x2.ge",
            BodyInstruction::V128Not => "v128.not",
            BodyInstruction::V128And => "v128.and",
            BodyInstruction::V128AndNot => "v128.andnot",
            BodyInstruction::V128Or => "v128.or",
            BodyInstruction::V128Xor => "v128.xor",
            BodyInstruction::V128Bitselect => "v128.bitselect",
            BodyInstruction::V128AnyTrue => "v128.any_true",
            BodyInstruction::I8x16Abs => "i8x16.abs",
            BodyInstruction::I8x16Neg => "i8x16.neg",
            BodyInstruction::I8x16Popcnt => "i8x16.popcnt",
            BodyInstruction::I8x16AllTrue => "i8x16.all_true",
            BodyInstruction::I8x16Bitmask => "i8x16.bitmask",
            BodyInstruction::I8x16NarrowI16x8S => "i8x16.narrow_i16x8_s",
            BodyInstruction::I8x16NarrowI16x8U => "i8x16.narrow_i16x8_u",
            BodyInstruction::I8x16Shl => "i8x16.shl",
            BodyInstruction::I8x16ShrS => "i8x16.shr_s",
            BodyInstruction::I8x16ShrU => "i8x16.shr_u",
            BodyInstruction::I8x16Add => "i8x16.add",
            BodyInstruction::I8x16AddSatS => "i8x16.add_sat_s",
            BodyInstruction::I8x16AddSatU => "i8x16.add_sat_u",
            BodyInstruction::I8x16Sub => "i8x16.sub",
            BodyInstruction::I8x16SubSatS => "i8x16.sub_sat_s",
            BodyInstruction::I8x16SubSatU => "i8x16.sub_sat_u",
            BodyInstruction::I8x16MinS => "i8x16.min_s",
            BodyInstruction::I8x16MinU => "i8x16.min_u",
            BodyInstruction::I8x16MaxS => "i8x16.max_s",
            BodyInstruction::I8x16MaxU => "i8x16.max_u",
            BodyInstruction::I8x16AvgrU => "i8x16.avgr_u",
            BodyInstruction::I16x8ExtAddPairwiseI8x16S => "i16x8.extadd_pairwise_i8x16_s",
            BodyInstruction::I16x8ExtAddPairwiseI8x16U => "i16x8.extadd_pairwise_i8x16_u",
            BodyInstruction::I16x8Abs => "i16x8.abs",
            BodyInstruction::I16x8Neg => "i16x8.neg",
            BodyInstruction::I16x8Q15MulrSatS => "i16x8.q15mulr_sat_s",
            BodyInstruction::I16x8AllTrue => "i16x8.all_true",
            BodyInstruction::I16x8Bitmask => "i16x8.bitmask",
            BodyInstruction::I16x8NarrowI32x4S => "i16x8.narrow_i32x4_s",
            BodyInstruction::I16x8NarrowI32x4U => "i16x8.narrow_i32x4_u",
            BodyInstruction::I16x8ExtendLowI8x16S => "i16x8.extend_low_i8x16_s",
            BodyInstruction::I16x8ExtendHighI8x16S => "i16x8.extend_high_i8x16_s",
            BodyInstruction::I16x8ExtendLowI8x16U => "i16x8.extend_low_i8x16_u",
            BodyInstruction::I16x8ExtendHighI8x16U => "i16x8.extend_high_i8x16_u",
            BodyInstruction::I16x8Shl => "i16x8.shl",
            BodyInstruction::I16x8ShrS => "i16x8.shr_s",
            BodyInstruction::I16x8ShrU => "i16x8.shr_u",
            BodyInstruction::I16x8Add => "i16x8.add",
            BodyInstruction::I16x8AddSatS => "i16x8.add_sat_s",
            BodyInstruction::I16x8AddSatU => "i16x8.add_sat_u",
            BodyInstruction::I16x8Sub => "i16x8.sub",
            BodyInstruction::I16x8SubSatS => "i16x8.sub_sat_s",
            BodyInstruction::I16x8SubSatU => "i16x8.sub_sat_u",
            BodyInstruction::I16x8Mul => "i16x8.mul",
            BodyInstruction::I16x8MinS => "i16x8.min_s",
            BodyInstruction::I16x8MinU => "i16x8.min_u",
            BodyInstruction::I16x8MaxS => "i16x8.max_s",
            BodyInstruction::I16x8MaxU => "i16x8.max_u",
            BodyInstruction::I16x8AvgrU => "i16x8.avgr_u",
            BodyInstruction::I16x8ExtMulLowI8x16S => "i16x8.extmul_low_i8x16_s",
            BodyInstruction::I16x8ExtMulHighI8x16S => "i16x8.extmul_high_i8x16_s",
            BodyInstruction::I16x8ExtMulLowI8x16U => "i16x8.extmul_low_i8x16_u",
            BodyInstruction::I16x8ExtMulHighI8x16U => "i16x8.extmul_high_i8x16_u",
            BodyInstruction::I32x4ExtAddPairwiseI16x8S => "i32x4.extadd_pairwise_i16x8_s",
            BodyInstruction::I32x4ExtAddPairwiseI16x8U => "i32x4.extadd_pairwise_i16x8_u",
            BodyInstruction::I32x4Abs => "i32x4.abs",
            BodyInstruction::I32x4Neg => "i32x4.neg",
            BodyInstruction::I32x4AllTrue => "i32x4.all_true",
            BodyInstruction::I32x4Bitmask => "i32x4.bitmask",
            BodyInstruction::I32x4ExtendLowI16x8S => "i32x4.extend_low_i16x8_s",
            BodyInstruction::I32x4ExtendHighI16x8S => "i32x4.extend_high_i16x8_s",
            BodyInstruction::I32x4ExtendLowI16x8U => "i32x4.extend_low_i16x8_u",
            BodyInstruction::I32x4ExtendHighI16x8U => "i32x4.extend_high_i16x8_u",
            BodyInstruction::I32x4Shl => "i32x4.shl",
            BodyInstruction::I32x4ShrS => "i32x4.shr_s",
            BodyInstruction::I32x4ShrU => "i32x4.shr_u",
            BodyInstruction::I32x4Add => "i32x4.add",
            BodyInstruction::I32x4Sub => "i32x4.sub",
            BodyInstruction::I32x4Mul => "i32x4.mul",
            BodyInstruction::I32x4MinS => "i32x4.min_s",
            BodyInstruction::I32x4MinU => "i32x4.min_u",
            BodyInstruction::I32x4MaxS => "i32x4.max_s",
            BodyInstruction::I32x4MaxU => "i32x4.max_u",
            BodyInstruction::I32x4DotI16x8S => "i32x4.dot_i16x8_s",
            BodyInstruction::I32x4ExtMulLowI16x8S => "i32x4.extmul_low_i16x8_s",
            BodyInstruction::I32x4ExtMulHighI16x8S => "i32x4.extmul_high_i16x8_s",
            BodyInstruction::I32x4ExtMulLowI16x8U => "i32x4.extmul_low_i16x8_u",
            BodyInstruction::I32x4ExtMulHighI16x8U => "i32x4.extmul_high_i16x8_u",
            BodyInstruction::I64x2Abs => "i64x2.abs",
            BodyInstruction::I64x2Neg => "i64x2.neg",
            BodyInstruction::I64x2AllTrue => "i64x2.all_true",
            BodyInstruction::I64x2Bitmask => "i64x2.bitmask",
            BodyInstruction::I64x2ExtendLowI32x4S => "i64x2.extend_low_i32x4_s",
            BodyInstruction::I64x2ExtendHighI32x4S => "i64x2.extend_high_i32x4_s",
            BodyInstruction::I64x2ExtendLowI32x4U => "i64x2.extend_low_i32x4_u",
            BodyInstruction::I64x2ExtendHighI32x4U => "i64x2.extend_high_i32x4_u",
            BodyInstruction::I64x2Shl => "i64x2.shl",
            BodyInstruction::I64x2ShrS => "i64x2.shr_s",
            BodyInstruction::I64x2ShrU => "i64x2.shr_u",
            BodyInstruction::I64x2Add => "i64x2.add",
            BodyInstruction::I64x2Sub => "i64x2.sub",
            BodyInstruction::I64x2Mul => "i64x2.mul",
            BodyInstruction::I64x2ExtMulLowI32x4S => "i64x2.extmul_low_i32x4_s",
            BodyInstruction::I64x2ExtMulHighI32x4S => "i64x2.extmul_high_i32x4_s",
            BodyInstruction::I64x2ExtMulLowI32x4U => "i64x2.extmul_low_i32x4_u",
            BodyInstruction::I64x2ExtMulHighI32x4U => "i64x2.extmul_high_i32x4_u",
            BodyInstruction::F32x4Ceil => "f32x4.ceil",
            BodyInstruction::F32x4Floor => "f32x4.floor",
            BodyInstruction::F32x4Trunc => "f32x4.trunc",
            BodyInstruction::F32x4Nearest => "f32x4.nearest",
            BodyInstruction::F32x4Abs => "f32x4.abs",
            BodyInstruction::F32x4Neg => "f32x4.neg",
            BodyInstruction::F32x4Sqrt => "f32x4.sqrt",
            BodyInstruction::F32x4Add => "f32x4.add",
            BodyInstruction::F32x4Sub => "f32x4.sub",
            BodyInstruction::F32x4Mul => "f32x4.mul",
            BodyInstruction::F32x4Div => "f32x4.div",
            BodyInstruction::F32x4Min => "f32x4.min",
            BodyInstruction::F32x4Max => "f32x4.max",
            BodyInstruction::F32x4PMin => "f32x4.pmin",
            BodyInstruction::F32x4PMax => "f32x4.pmax",
            BodyInstruction::F64x2Ceil => "f64x2.ceil",
            BodyInstruction::F64x2Floor => "f64x2.floor",
            BodyInstruction::F64x2Trunc => "f64x2.trunc",
            BodyInstruction::F64x2Nearest => "f64x2.nearest",
            BodyInstruction::F64x2Abs => "f64x2.abs",
            BodyInstruction::F64x2Neg => "f64x2.neg",
            BodyInstruction::F64x2Sqrt => "f64x2.sqrt",
            BodyInstruction::F64x2Add => "f64x2.add",
            BodyInstruction::F64x2Sub => "f64x2.sub",
            BodyInstruction::F64x2Mul => "f64x2.mul",
            BodyInstruction::F64x2Div => "f64x2.div",
            BodyInstruction::F64x2Min => "f64x2.min",
            BodyInstruction::F64x2Max => "f64x2.max",
            BodyInstruction::F64x2PMin => "f64x2.pmin",
            BodyInstruction::F64x2PMax => "f64x2.pmax",
            BodyInstruction::I32x4TruncSatF32x4S => "i32x4.trunc_sat_f32x4_s",
            BodyInstruction::I32x4TruncSatF32x4U => "i32x4.trunc_sat_f32x4_u",
            BodyInstruction::F32x4ConvertI32x4S => "f32x4.convert_i32x4_s",
            BodyInstruction::F32x4ConvertI32x4U => "f32x4.convert_i32x4_u",
            BodyInstruction::I32x4TruncSatF64x2SZero => "i32x4.trunc_sat_f64x2_s_zero",
            BodyInstruction::I32x4TruncSatF64x2UZero => "i32x4.trunc_sat_f64x2_u_zero",
            BodyInstruction::F64x2ConvertLowI32x4S => "f64x2.convert_low_i32x4_s",
            BodyInstruction::F64x2ConvertLowI32x4U => "f64x2.convert_low_i32x4_u",
            BodyInstruction::F32x4DemoteF64x2Zero => "f32x4.demote_f64x2_zero",
            BodyInstruction::F64x2PromoteLowF32x4 => "f64x2.promote_low_f32x4",
            BodyInstruction::I8x16RelaxedSwizzle => "i8x16.relaxed_swizzle",
            BodyInstruction::I32x4RelaxedTruncF32x4S => "i32x4.relaxed_trunc_f32x4_s",
            BodyInstruction::I32x4RelaxedTruncF32x4U => "i32x4.relaxed_trunc_f32x4_u",
            BodyInstruction::I32x4RelaxedTruncF64x2SZero => "i32x4.relaxed_trunc_f64x2_s_zero",
            BodyInstruction::I32x4RelaxedTruncF64x2UZero => "i32x4.relaxed_trunc_f64x2_u_zero",
            BodyInstruction::F32x4RelaxedMadd => "f32x4.relaxed_madd",
            BodyInstruction::F32x4RelaxedNmadd => "f32x4.relaxed_nmadd",
            BodyInstruction::F64x2RelaxedMadd => "f64x2.relaxed_madd",
            BodyInstruction::F64x2RelaxedNmadd => "f64x2.relaxed_nmadd",
            BodyInstruction::I8x16RelaxedLaneselect => "i8x16.relaxed_laneselect",
            BodyInstruction::I16x8RelaxedLaneselect => "i16x8.relaxed_laneselect",
            BodyInstruction::I32x4RelaxedLaneselect => "i32x4.relaxed_laneselect",
            BodyInstruction::I64x2RelaxedLaneselect => "i64x2.relaxed_laneselect",
            BodyInstruction::F32x4RelaxedMin => "f32x4.relaxed_min",
            BodyInstruction::F32x4RelaxedMax => "f32x4.relaxed_max",
            BodyInstruction::F64x2RelaxedMin => "f64x2.relaxed_min",
            BodyInstruction::F64x2RelaxedMax => "f64x2.relaxed_max",
            BodyInstruction::I16x8RelaxedQ15mulrS => "i16x8.relaxed_q15mulr_s",
            BodyInstruction::I16x8RelaxedDotI8x16I7x16S => "i16x8.relaxed_dot_i8x16_i7x16_s",
            BodyInstruction::I32x4RelaxedDotI8x16I7x16AddS => "i32x4.relaxed_dot_i8x16_i7x16_add_s",
            BodyInstruction::TryTable => "try_table",
            BodyInstruction::Throw => "throw",
            BodyInstruction::ThrowRef => "throw_ref",
            BodyInstruction::Try => "try",
            BodyInstruction::Catch => "catch",
            BodyInstruction::Rethrow => "rethrow",
            BodyInstruction::Delegate => "delegate",
            BodyInstruction::CatchAll => "catch_all",
            BodyInstruction::GlobalAtomicGet => "global.atomic.get",
            BodyInstruction::GlobalAtomicSet => "global.atomic.set",
            BodyInstruction::GlobalAtomicRmwAdd => "global.atomic.rmw.add",
            BodyInstruction::GlobalAtomicRmwSub => "global.atomic.rmw.sub",
            BodyInstruction::GlobalAtomicRmwAnd => "global.atomic.rmw.and",
            BodyInstruction::GlobalAtomicRmwOr => "global.atomic.rmw.or",
            BodyInstruction::GlobalAtomicRmwXor => "global.atomic.rmw.xor",
            BodyInstruction::GlobalAtomicRmwXchg => "global.atomic.rmw.xchg",
            BodyInstruction::GlobalAtomicRmwCmpxchg => "global.atomic.rmw.cmpxchg",
            BodyInstruction::TableAtomicGet => "table.atomic.get",
            BodyInstruction::TableAtomicSet => "table.atomic.set",
            BodyInstruction::TableAtomicRmwXchg => "table.atomic.rmw.xchg",
            BodyInstruction::TableAtomicRmwCmpxchg => "table.atomic.rmw.cmpxchg",
            BodyInstruction::StructAtomicGet => "struct.atomic.get",
            BodyInstruction::StructAtomicGetS => "struct.atomic.get_s",
            BodyInstruction::StructAtomicGetU => "struct.atomic.get_u",
            BodyInstruction::StructAtomicSet => "struct.atomic.set",
            BodyInstruction::StructAtomicRmwAdd => "struct.atomic.rmw.add",
            BodyInstruction::StructAtomicRmwSub => "struct.atomic.rmw.sub",
            BodyInstruction::StructAtomicRmwAnd => "struct.atomic.rmw.and",
            BodyInstruction::StructAtomicRmwOr => "struct.atomic.rmw.or",
            BodyInstruction::StructAtomicRmwXor => "struct.atomic.rmw.xor",
            BodyInstruction::StructAtomicRmwXchg => "struct.atomic.rmw.xchg",
            BodyInstruction::StructAtomicRmwCmpxchg => "struct.atomic.rmw.cmpxchg",
            BodyInstruction::ArrayAtomicGet => "array.atomic.get",
            BodyInstruction::ArrayAtomicGetS => "array.atomic.get_s",
            BodyInstruction::ArrayAtomicGetU => "array.atomic.get_u",
            BodyInstruction::ArrayAtomicSet => "array.atomic.set",
            BodyInstruction::ArrayAtomicRmwAdd => "array.atomic.rmw.add",
            BodyInstruction::ArrayAtomicRmwSub => "array.atomic.rmw.sub",
            BodyInstruction::ArrayAtomicRmwAnd => "array.atomic.rmw.and",
            BodyInstruction::ArrayAtomicRmwOr => "array.atomic.rmw.or",
            BodyInstruction::ArrayAtomicRmwXor => "array.atomic.rmw.xor",
            BodyInstruction::ArrayAtomicRmwXchg => "array.atomic.rmw.xchg",
            BodyInstruction::ArrayAtomicRmwCmpxchg => "array.atomic.rmw.cmpxchg",
            BodyInstruction::RefI31Shared => "ref.i31_shared",
            BodyInstruction::CallRef => "call_ref",
            BodyInstruction::ReturnCallRef => "return_call_ref",
            BodyInstruction::RefAsNonNull => "ref.as_non_null",
            BodyInstruction::BrOnNull => "br_on_null",
            BodyInstruction::BrOnNonNull => "br_on_non_null",
            BodyInstruction::ContNew => "cont.new",
            BodyInstruction::ContBind => "cont.bind",
            BodyInstruction::Suspend => "suspend",
            BodyInstruction::Resume => "resume",
            BodyInstruction::ResumeThrow => "resume_throw",
            BodyInstruction::Switch => "switch",
            BodyInstruction::I64Add128 => "i64.add128",
            BodyInstruction::I64Sub128 => "i64.sub128",
            BodyInstruction::I64MulWideS => "i64.mul_wide_s",
            BodyInstruction::I64MulWideU => "i64.mul_wide_u",
        }
    }
}
